version: '3.4'

services:
  project1:
    image: project1
    build:
      context: react-config
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8888:8888
