version: '3.4'

services:
  project1:
    image: project1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
